### ISSUE TITLE
TypeError: Cannot read property 'trigger' of undefined

### ISSUE THREAD

**Issue by dandrzejewski** [civicrm/org.civicrm.volunteer#495]
This bug was filed under angularprofiles, but may belong here: https://github.com/ginkgostreet/org.civicrm.angularprofiles/issues/16

**Comment by dandrzejewski** [comment]
I managed to fix this, I think.  But I'm not a JavaScript guy and it feels dirty.  Works for me, however.

https://github.com/ginkgostreet/org.civicrm.angularprofiles/issues/16#issuecomment-459128703

**Comment by universalhandle** [comment]
Closing as there is more detail in the other issue.
