### ISSUE TITLE
Error: Expected one VolunteerNeed but found 3

### ISSUE THREAD

**Issue by dandrzejewski** [civicrm/org.civicrm.volunteer#504]
When searching for volunteer opportunities, the error "Expected one VolunteerNeed but found 3" is displayed.  I'm running the latest CiviVolunteer from the civicrm plugin site with CiviCRM 5.11.0.

What other information can I include for troubleshooting?

**Comment by ginkgomzd** [comment]
huh, interesting.
In terms of the opportunity search, there is only one VolunteerNeed.getSingle...
https://github.com/civicrm/org.civicrm.volunteer/blob/master/CRM/Volunteer/BAO/NeedSearch.php#L73

So, my best guess is that your project, or projects, are somehow missing their flexible needs.
This is the implicit need that is used when "Allow users to sign-up without specifying a shift" is selected on the project config.

How many projects do you have configured? How many of those are using the above option?
Do you have one or many Volunteer Projects?

**Comment by dandrzejewski** [comment]
I ended up deleting all of the volunteer projects (fortunately nothing live yet) and recreating one, the error seems to have gone away.  I tried to reproduce it and am now unable to - so I'll close this, and if I manage to get it to happen, I'll re-open.
