### ISSUE TITLE
Not filtering out opportunities

### ISSUE THREAD

**Issue by kelizoliva** [civicrm/org.civicrm.volunteer#520]
This is when using the 2.5-rc branch, with all commits from Mar 28, 2019 and before (have not pulled in most recent commits yet, will do today). When the user clicks "Volunteer Now" on any volunteer page, the resulting opportunity lest does not filter by event id (which is included in the link), but instead shows all volunteer opportunities.

The only log messages I am seeing when loading the list are:

```
Sep 11 14:23:43  [warning] Deprecated function CRM_Core_OptionGroup::getValue, use CRM_Core_PseudoConstant::getKey.
Array
(
    [civi.tag] => deprecated
)
```

But this is unrelated to the issue.

**Comment by ginkgomzd** [comment]
Thanks for reporting this! These are both issues I know we resolved in our custom fork.
I'll go looking for these fixes and add them to the release.

**Comment by kelizoliva** [comment]
Thanks!

**Comment by palantewebtickets** [comment]
Curious if you were able to locate these fixes?

**Comment by elizolivares** [comment]
Curious if you were able to locate these fixes?

**Comment by kelizoliva** [comment]
I have way too many github accounts; that was me ^

**Comment by ginkgomzd** [comment]
okay, added some cherry-picked commits to 2.5-rc
https://github.com/civicrm/org.civicrm.volunteer/commits/2.5-rc

I'm not sure about linking by event-id. What we fixed was filtering by project-id.
Does your URL use, "?project=NN" ?

**Comment by kelizoliva** [comment]
Yup, this is by project id, not event id. I will deploy the changes and test, thanks!

**Comment by kelizoliva** [comment]
Issue appears resolved with this update, thanks for digging that out!
