### ISSUE TITLE
Move this repo and Issue tracking to GitLab - lab.civicrm.org ?

### ISSUE THREAD

**Issue by joemcl** [civicrm/org.civicrm.volunteer#529]
The readme here refers to Issue Tracking on Jira, which we have deprecated. Seems like time to move this repo to GitLab - lab.civicrm.org -  and do Issue Tracking etc there?

**Comment by ginkgomzd** [comment]
I don't understand the benefits of CiviCRM's GitLab.
The README should be updated to indicate that issues can be filed here.
