### ISSUE TITLE
 Angular fails to run volunteer

### ISSUE THREAD

**Issue by iseimandi** [civicrm/org.civicrm.volunteer#538]
We install civic.volunteer version: 4.7.31-2.3.1 along with Angular Profiles Version extension: 4.7.31-1.1.2. We use CiviCRM over Drupal.
When opening the "New volunteer project" or "Manage Volunter Project" forms from the Volunteer menu I get the following error: Error: Class 'Civi \ Angular \ AngularLoader' not found in CRM_Volunteer_Angular :: load () (line 27 of / data / civicrm / files / civicrm / ext / org.civicrm.volunteer-4.7.31-2.3.1 / CRM / Volunteer / Angular.php).
Let's check that the directory and url paths match, we wipe cache and the problem persists. Can someone please give us a hint of where we may have the problem? Many thanks!

**Comment by ginkgomzd** [comment]
Hi Ivana,
What version of CiviCRM are you running?
I don't think this sounds like a problem that would be resolved by installing the master-branch of the extension, but you could try that.
It does sound like an issue with the AngularProfiles extension. Did you install both extensions through the UI? If not, there might be file system permissions problems.

I have seen that the CiviCRM caches sometimes do not get cleared. If you see any files starting with `CachedExtensionloader...` in the `templates_c` folder immediately after clearing caches, then that might be the problem It is safe to delete all files in `templates_c`

Saludos
