### ISSUE TITLE
Offering to maintain/co-maintain CiviVolunteer

### ISSUE THREAD

**Issue by MikeyMJCO** [civicrm/org.civicrm.volunteer#543]
I'd like to offer to maintain or co-maintain CiviVolunteer, with a view to moving it to GitLab and opening up maintainership to a wider group of devs in the community who use the extension.

We're increasing our use of CiviVolunteer and compatibility issues creeping in between Volunteer and CiviCRM 5.25.x are causing log noise and we'd rather get ahead of these issues.

**Comment by ginkgomzd** [comment]
Hi Mikey,
I would love to talk about co-maintaining VOL. Glad to hear you are expanding your usage.
I don't understand what "opening up mainternship" means, but I have always been looking for contributions and collaboration.

Let's set a call next week? What's good for you?

**Comment by MikeyMJCO** [comment]
I can do any day except Thursday next week (I'm UK timezone.) When I say opening up maintainership I guess I'm talking actively encouraging/soliciting those who use CiviVolunteer to step up and help co-maintain, fix issues, propose patches. There are a few organisations I know of using CiviVolunteer who have patches/fixes but haven't (for whatever reason) contributed them back - so I'd like to try doing some outreach to people using CiviVolunteer :-)

**Comment by ginkgomzd** [comment]
I would really appreciate submission of patches, even if they aren't suitable for merging.

What we really need is testing and bug-fixes of the RC.

I'll shoot you a message on Mattermost to set up the meeting.

**Comment by MikeyMJCO** [comment]
Sounds good!
