### ISSUE TITLE
Cannot access some Volunteer functionality 

### ISSUE THREAD

**Issue by gcpower** [civicrm/org.civicrm.volunteer#552]
The is the summary of actions and responses:New Volunteer Project
CiviVolunteer and nothing else displayed

Manage Volunteer Projects
relationship_type_id is not a valid integer

Configure Roles
Working

Configure Project Relationships
getFieldValue failed 

Configure volunteer Settings
'volunteer_project_relationship' is not a valid option for field option_group_id

Volunteer Interest Form
Form displays

Search for Volunteer Opportunities
Form working

This is the link on StackExchange [https://civicrm.stackexchange.com/questions/38964/civi-volunteer-2-4-1-fatal-errors-on-install-civicrm-5-33-2-drupal-7-78](url)

This is the output from the log file:
$Fatal Error Details = array:3 [ "message" => "'volunteer_project_relationship' is not a valid option for field option_group_id" "code" => null "exception" => CiviCRM_API3_Exception {#1442 -extraParams: array:6 [ "error_field" => "option_group_id" "error_code" => 2001 "entity" => "OptionValue" "action" => "get" "is_error" => 1 "error_message" => "'volunteer_project_relationship' is not a valid option for field option_group_id" ] #message: "'volunteer_project_relationship' is not a valid option for field option_group_id" #code: 0 #file: "/home/webdevelopmentsc/public_html/sites/all/modules/civicrm/api/api.php" #line: 133 trace: { /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/api/api.php:133 { › if (is_array($result) && !empty($result['is_error'])) { › throw new CiviCRM_API3_Exception($result['error_message'], CRM_Utils_Array::value('error_code', $result, 'undefined'), $result); › } } /home/webdevelopmentsc/public_html/sites/default/files/civicrm/ext/org.civicrm.volunteer/CRM/Volunteer/Form/Settings.php:428 { …} /home/webdevelopmentsc/public_html/sites/default/files/civicrm/ext/org.civicrm.volunteer/CRM/Volunteer/Form/Settings.php:179 { …} /home/webdevelopmentsc/public_html/sites/default/files/civicrm/ext/org.civicrm.volunteer/CRM/Volunteer/Form/Settings.php:119 { …} /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Core/Form.php:629 { …} /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Display.php:76 { …} /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php:203 { …} /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php:103 { …} /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Core/Controller.php:347 { …} /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Utils/Wrapper.php:98 { …} /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php:285 { …} /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php:68 { …} /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php:36 { …} /home/webdevelopmentsc/public_html/sites/all/modules/civicrm/drupal/civicrm.module:459 { …} /home/webdevelopmentsc/public_html/includes/menu.inc:527 { …} /home/webdevelopmentsc/public_html/index.php:21 { …} } } ]

I would appreciate any help.  Thank you

**Comment by ginkgomzd** [comment]
Treating this as a support request until there is clearer evidence of incompatibility with a new CiviCRM Release.

https://civicrm.stackexchange.com/questions/38964/civi-volunteer-2-4-1-fatal-errors-on-install-civicrm-5-33-2-drupal-7-78
