### ISSUE TITLE
Blank pages and errors on fresh WordPress install

### ISSUE THREAD

**Issue by ChrisHardie** [civicrm/org.civicrm.volunteer#557]
Hi. Just tried installing Volunteer on top of a CiviCRM 5.35.1 install using WordPress 5.7. The install (along with Angular) went fine, but when I go to "New Volunteer Project" I'm presented with a briefly appearing Civi logo spinner and then a mostly blank page:

![Screen Shot 2021-04-05 at 12 09 53](https://user-images.githubusercontent.com/311772/113596126-dce71000-9607-11eb-9880-7c6fa7cf9108.png)

There are no JS/console errors. Ad blocking is disabled.

I can get to the "Configure Roles" page fine. "Configure Project Relationships" gives an error:

> Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
> getFieldValue failed

Visiting "Configure Volunteer Settings" gives an error:

> Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
> 'volunteer_project_relationship' is not a valid option for field option_group_id

The "Volunteer Interest Form" loads but shows the error:

> Error getFieldValue failed

I tried starting fresh (as in, resetting the DB to its prior state and removing the extension files) and got the same errors.

Am I missing something about how to install/configure this extension? Any help is much appreciated. Thanks.

**Comment by ginkgomzd** [comment]
Thanks for reporting.

This has a lot in common with the symptoms of #552 
I haven't been able to reliably produce this and a fresh re-install resolved it in that case.

You can try the work-around here: https://civicrm.stackexchange.com/questions/38964/civi-volunteer-2-4-1-fatal-errors-on-install-civicrm-5-33-2-drupal-7-78

Do you have full logging enabled when doing the extension install?
