### ISSUE TITLE
Release date in info.xml is 2018

### ISSUE THREAD

**Issue by demeritcowboy** [civicrm/org.civicrm.volunteer#566]
So it lists out of order at https://civicrm.org/extensions/civivolunteer

And on the public demo it seems to still have 2.4.1 installed although might just be a timing issue between when 2.4.3 was released and the demo rebuilt.

**Comment by ginkgomzd** [comment]
Thanks, I will double-check the date on the next release. 

I deleted the 2.4.2 release on the extension directory since it should not be useful to anyone.

I'm not aware of how the version on demo is being managed.
