### ISSUE TITLE
Example in docs no longer using CiviVolunteer

### ISSUE THREAD

**Issue by HikerBoricua** [civicrm/org.civicrm.volunteer#567]
The one example in org.civicrm.volunteer/docs/examples.md ([published](https://docs.civicrm.org/volunteer/en/latest/examples/)) results in "Page not found." Hunger Free America is now using [volunteerhub.com](https://hungervolunteer.volunteerhub.com/).

**Comment by ginkgomzd** [comment]
link was removed from doc
