### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by nickchu852** [civicrm/org.civicrm.volunteer#601]
CRM_Core_Exception: DB Error: unknown error in /var/www/i2srpm_internal_v2/vendor/civicrm/civicrm-core/CRM/Admin/Form/Extensions.php on line 187

Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
DB Error: unknown error

**Comment by ginkgomzd** [comment]
I think the solution is likely the work-around discussed on PR #592.

Please provide more information if this is unrelated, or if you make any new discoveries about that issue. 

Thanks for reporting.
