### ISSUE TITLE
Installing Civivolunteer 2.4.5 for Civicrm version 5.73.2 gives errors

### ISSUE THREAD

**Issue by AxelvdS** [civicrm/org.civicrm.volunteer#603]
I can't install CiviVolunteer (2.4.5) for CiviCRM (5.73.2) and have tried in a running version and also after a fresh install and get the same errors:
1. `DB Error: unknown error` and I have changed the field frontend_title to 'Default NULL' in the database so I could retrry the install. The next run the following error showed and the install failed
2. `CRM_Core_Exception: Unable to load template 'file:volunteer-customdata.xml.tpl' in /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Admin/Form/Extensions.php on line 187`

Can you please help?

Ad 1. the details are:
2024-05-20 06:53:45+0000  [error] 
$Fatal Error Details = array:3 [
  "message" => "DB Error: unknown error"
  "code" => null
  "exception" => CRM_Core_Exception {#2497
    #message: "DB Error: unknown error"
    #code: -1
    #file: "/home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/api/api.php"
    #line: 138
    #cause: null
    -_trace: null
    -errorData: array:8 [
      "error_code" => -1
      "sql" => "INSERT INTO `civicrm_uf_group` (`name` , `is_active` , `group_type` , `title` , `add_captcha` , `is_map` , `is_edit_link` , `is_uf_link` , `is_update_dupe` , `is_reserved` , `is_proximity_search` ) VALUES ('volunteer_sign_up' ,  1 , 'Individual,Contact' , 'Volunteer Sign Up' ,  0 ,  0 ,  0 ,  0 ,  1 ,  1 ,  0 ) "
      "debug_info" => "INSERT INTO `civicrm_uf_group` (`name` , `is_active` , `group_type` , `title` , `add_captcha` , `is_map` , `is_edit_link` , `is_uf_link` , `is_update_dupe` , `is_reserved` , `is_proximity_search` ) VALUES ('volunteer_sign_up' ,  1 , 'Individual,Contact' , 'Volunteer Sign Up' ,  0 ,  0 ,  0 ,  0 ,  1 ,  1 ,  0 )  [nativecode=1364 ** Field 'frontend_title' doesn't have a default value]"
      "entity" => "Extension"
      "action" => "install"
      "is_error" => 1
      "error_message" => "DB Error: unknown error"
      "debug_information" => "INSERT INTO `civicrm_uf_group` (`name` , `is_active` , `group_type` , `title` , `add_captcha` , `is_map` , `is_edit_link` , `is_uf_link` , `is_update_dupe` , `is_reserved` , `is_proximity_search` ) VALUES ('volunteer_sign_up' ,  1 , 'Individual,Contact' , 'Volunteer Sign Up' ,  0 ,  0 ,  0 ,  0 ,  1 ,  1 ,  0 ) "
    ]
    trace: {
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/api/api.php:138 {
        civicrm_api3(string $entity, string $action, array $params = [])
        › if (is_array($result) && !empty($result['is_error'])) {
        ›   throw new CRM_Core_Exception($result['error_message'], $result['error_code'] ?? 'undefined', $result);
        › }
      }
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Admin/Form/Extensions.php:187 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php:646 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Core/StateMachine.php:144 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Next.php:43 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php:203 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php:103 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php:355 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Core/Page/Basic.php:364 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Core/Page/Basic.php:170 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Admin/Page/Extensions.php:110 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:325 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:69 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:36 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm.php:1231 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-includes/class-wp-hook.php:324 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-includes/class-wp-hook.php:348 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-includes/plugin.php:517 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-admin/admin.php:259 { …}
    }
  }
]

Ad 2. the details are:

2024-05-20 07:33:11+0000  [error] 
$Fatal Error Details = array:3 [
  "message" => "Unable to load template 'file:volunteer-customdata.xml.tpl'"
  "code" => null
  "exception" => CRM_Core_Exception {#2555
    #message: "Unable to load template 'file:volunteer-customdata.xml.tpl'"
    #code: 0
    #file: "/home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/api/api.php"
    #line: 138
    #cause: null
    -_trace: null
    -errorData: array:3 [
      "is_error" => 1
      "error_message" => "Unable to load template 'file:volunteer-customdata.xml.tpl'"
      "error_code" => "undefined"
    ]
    trace: {
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/api/api.php:138 {
        civicrm_api3(string $entity, string $action, array $params = [])
        › if (is_array($result) && !empty($result['is_error'])) {
        ›   throw new CRM_Core_Exception($result['error_message'], $result['error_code'] ?? 'undefined', $result);
        › }
      }
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Admin/Form/Extensions.php:187 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php:646 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Core/StateMachine.php:144 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Next.php:43 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php:203 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php:103 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php:355 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Core/Page/Basic.php:364 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Core/Page/Basic.php:170 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Admin/Page/Extensions.php:110 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:325 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:69 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:36 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm.php:1231 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-includes/class-wp-hook.php:324 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-includes/class-wp-hook.php:348 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-includes/plugin.php:517 { …}
      /home/vanders/ftm.vandersmagt.com.au/wp-admin/admin.php:259 { …}
    }
  }
]

2024-05-20 07:33:11+0000  [debug] $backTrace = #0 /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php(443): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(39): CRM_Core_Error::handleUnhandledException(Object(CRM_Core_Exception))
#2 /home/vanders/ftm.vandersmagt.com.au/wp-content/plugins/civicrm/civicrm.php(1231): CRM_Core_Invoke::invoke((Array:3))
#3 /home/vanders/ftm.vandersmagt.com.au/wp-includes/class-wp-hook.php(324): CiviCRM_For_WordPress->invoke("")
#4 /home/vanders/ftm.vandersmagt.com.au/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters("", (Array:1))
#5 /home/vanders/ftm.vandersmagt.com.au/wp-includes/plugin.php(517): WP_Hook->do_action((Array:1))
#6 /home/vanders/ftm.vandersmagt.com.au/wp-admin/admin.php(259): do_action("toplevel_page_CiviCRM")
#7 {main}

**Comment by ginkgomzd** [comment]
It would be a service to the community if you are able to confirm how to reproduce this scenario and get at the root cause. Troubleshooting this should involve an experienced sysadmin with access to your system.

If you can not hire someone, you could try getting support in the CiviCRM Stack Exchange or Mattermost. You can peruse the Experts directory on CiviCRM.Org to find paid support.

Cheers

**Comment by AxelvdS** [comment]
I have worked out that Civivolunteer is compatible with CiviCRM 5.6x and not with 5.7x
Will there be an update?

**Comment by ginkgomzd** [comment]
okay, I will give it some time next week.

Do you think that you have confirmed the problem exists on a fresh install?
There has been an installer bug in the case of a reinstall or after a failed install that has been elusive for some time.

Any amount of funding you can provide would help me to devote more time. There has been no financial support for this extension in some time.

**Comment by AxelvdS** [comment]
Hi,I am trying to convince an organization to start using Civicrm with Civivolunteer and have followed these steps:1. Installed civivolunteer on a running demo environment which caused the errors2. Set up a new 5.73.2 environment and when trying to install civivolunteer I encountered the exact same errors3.installed a new Civicrm 5.69.5 environment and then installed Civivolunteer which went fineI’m doing this work unpaid so unfortunately have no funding to help you. What I can do is help you with my time. I have experience with php, js and html. Regards, AxelOn 21 May 2024, at 23:52, Michael Z Daryabeygi ***@***.***> wrote:﻿
okay, I will give it some time next week.
Do you think that you have confirmed the problem exists on a fresh install?
There has been an installer bug in the case of a reinstall or after a failed install that has been elusive for some time.
Any amount of funding you can provide would help me to devote more time. There has been no financial support for this extension in some time.
