### ISSUE TITLE
create new volunteer not work

### ISSUE THREAD

**Issue by nickchu852** [civicrm/org.civicrm.volunteer#605]
civicrm/vol#/volunteer/manage/0

i try go to create page, but no any form on this page
![01](https://github.com/civicrm/org.civicrm.volunteer/assets/109526898/7cc76662-fe92-4d89-9d7e-f8115a6e5494)

**Comment by ginkgomzd** [comment]
Not enough information provided. This feels like a core configuration issue. Double-check your directory paths and URL configs. There are probably errors displayed in the browser console. Dependencies are probably not loaded.
