### ISSUE TITLE
Unable to install on dmaster.demo.civicrm.org

### ISSUE THREAD

**Issue by petednz** [civicrm/org.civicrm.volunteer#609]
after enabling Angular Profiles and then trying to install this extension i get "The website encountered an unexpected error. Please try again later."

I enabled the Log Viewer and retried and again got above error but nothing showing in View Log.

Maybe something in Drupal logs but can't access them

**Comment by mlutfy** [comment]
Here is a fix: https://github.com/civicrm/org.civicrm.volunteer/pull/617

I will close this issue in favour of #615

**Comment by stesi561** [comment]
Will need this as a fix as well I believe. https://github.com/civicrm/org.civicrm.volunteer/pull/618
