### ISSUE TITLE
New Volunteer Project fails to render properly after page reload

### ISSUE THREAD

**Issue by messica** [civicrm/org.civicrm.volunteer#613]
A client has been having an issue where the New Volunteer Project page fails to render properly after the page is reloaded -- it only works once after clearing all caches via `cv flush` or the System.flush API call, then refreshing the page breaks it again.

![Screen Shot 2024-09-06 at 7 26 47 PM](https://github.com/user-attachments/assets/c28045e6-6eac-4013-bf63-07b3f0b97948)

This error shows in the Console:
`angular.js:15697 TypeError: Cannot read properties of undefined (reading 'entityTable')
    at setFormDefaults (angular-modules.fae853a00d962529bcdd5a9f326dfe43.js:2051:47)
    at new <anonymous> (angular-modules.fae853a00d962529bcdd5a9f326dfe43.js:2063:5)
    at Object.instantiate (angular.js:5223:14)
    at angular.js:11829:18
    at Object.link (angular-modules.fae853a00d962529bcdd5a9f326dfe43.js:1668:217)
    at angular.js:1391:15
    at Ca (angular.js:11376:9)
    at p (angular.js:10695:11)
    at g (angular.js:9942:13)
    at angular.js:9807:30 '<div ng-view="" class="ng-scope">'`

I was able to trace the issue to CiviCRM 5.69.0 with git bisect, so I suspect it has something to do with the [changes made to how Angular modules are cached](https://github.com/civicrm/civicrm-core/pull/27783) but I didn't spend too much time digging. Also, I have not attempted to recreate this issue on a clean CiviCRM install.

**Comment by jmcclelland** [comment]
I'm experiencing the same problem and after seeing your post, also think it's the cache. If I run `cv flush` and reload the page it works. But if I reload it again, it fails. In my console I get:

```
TypeError: CRM.vars['org.civicrm.volunteer'] is undefined
```

**Comment by jmcclelland** [comment]
@colemanw Do you have any thoughts on how to fix what appears to be a afform caching problem with civivolunteer?

**Comment by colemanw** [comment]
@jmcclelland sure ^

**Comment by jmcclelland** [comment]
@colemanw Thank you!!

**Comment by colemanw** [comment]
@jmcclelland when you get a chance to test & verify it works pls leave a review comment on the PR.

**Comment by jmcclelland** [comment]
@colemanw Tested and it works. Thanks again!
