### ISSUE TITLE
Ability to post page for volunteers to self report hours?

### ISSUE THREAD

**Issue by broswell** [civicrm/org.civicrm.volunteer#620]
I see how I can login and add hours, but I don't see a way for non-administrators.

I had expected that I could add a WordPress page, click on the CiviCRM button, and insert the hours form  on a page someplace.
And I missing something?

Bob Roswell

**Comment by ginkgomzd** [comment]
Please look for support in https://civicrm.stackexchange.com/ or https://chat.civicrm.org

**Comment by ginkgomzd** [comment]
No, the feature is just for staff, not volunteers. You will have to build a custom public-facing form to enable volunteers to log time.
